### ISSUE TITLE
x3dOpacity test fails

### ISSUE THREAD

**Issue by dnvasilev** [gearvrf/GearVRf-Tests#145]
In the image below, the overlaying square is 50% transparent and text should show through
X3D source:  https://github.com/gearvrf/GearVRf-Tests/blob/master/x3d/general/opacitytest01.x3d
![x3dopacity](https://user-images.githubusercontent.com/21369890/30296857-7ffb6900-96fa-11e7-9c6f-ed868ed7e410.png)

**Comment by dnvasilev** [comment]
Load the same model in gvr-x3d-demo and the output is correct.
Chances are rendering order is not set to 'transparent'

**Comment by mwitchwilliams** [comment]
Here are the screen shots when using gvr-x3d-demo from the demo's repo:
First image is when GVRRenderingOrder set to TRANSPARENT and the second image GVRRenderingOrder set to GEOMETRY.  I also commented out reference to the headlight and cursor in X3DparserScript.java just to insure it didn't impact the image (which was seriously doubtful anyway).  X3DparserScript.java does call `onStep() {FPSCounter.tick(); }`

It does look like TRANSPARENT blended in the background even when against an opaque object, but GEOMETRY does not.

![renderorder_transparent](https://user-images.githubusercontent.com/18128830/30336492-2f621d90-979a-11e7-856d-020e80d21869.png)
![renderorder_geometry](https://user-images.githubusercontent.com/18128830/30336499-3343b374-979a-11e7-8f22-84fd84e22d0a.png)

**Comment by mwitchwilliams** [comment]
Pull Request https://github.com/Samsung/GearVRf/pull/1446 that has been merged to change the RenderingOrder from TRANSPARENCY to GEOMETRY that appears to correct this issue.
