### ISSUE TITLE
x3dPointLight2 different in Release 4.0

### ISSUE THREAD

**Issue by dnvasilev** [gearvrf/GearVRf-Tests#190]
The dog texture is upside down.
asset-tests  AssetLightTest x3dPointLight2
Result:
![x3dpoint2](https://user-images.githubusercontent.com/21369890/31257405-3ac5b51a-a9ed-11e7-8dfb-d3032e347bb2.png)

Diff:
![diff_x3dpoint2](https://user-images.githubusercontent.com/21369890/31257419-479931c2-a9ed-11e7-894f-cad196a09432.png)

Correct image from Release 3.3:
![x3dpoint2](https://user-images.githubusercontent.com/21369890/31257471-89ae011e-a9ed-11e7-8d21-a34c889ebcad.png)

**Comment by dnvasilev** [comment]
Found code that is in maint_v3.3, but not in master.
X3Dobject.java, line 3670:

                if (hasTexcoords) // flip the Y texture coordinate
                {
                    t = 2 * i;
                    newTexcoords[t] = gvrTexcoords.get(t++);
                    newTexcoords[t] = maxMinDiff - gvrTexcoords.get(t);
                }

**Comment by dnvasilev** [comment]
3.3 flips texture coordinate in X3Dobject.UserHandler.organizeVertices()
4.0 reformed code uses X3Dobject.MeshCreator.copyVertices() called from organizeVertices(). The y-coordinate flip code is missing.

**Comment by dnvasilev** [comment]
4.0: organizeVertices() computes minYtextureCoordinate and maxYtextureCoordinate, but never uses them. They are needed only for texture flip.

**Comment by mwitchwilliams** [comment]
Repeatable issue.
Actually, texture coordinates need not be 0 and 1.  They can be from 0.7 to 3.6 for example.  And thus the maxMinDiff value in the code above.
New MeshCreator class was replaced the X3D's implementation of GVRMesh.

**Comment by dnvasilev** [comment]
Fixed Samsung/GearVRf#1509
