### ISSUE TITLE
StateSortTests fail on 4.0

### ISSUE THREAD

**Issue by dnvasilev** [gearvrf/GearVRf-Tests#192]
'class gvr::Renderer' has no member named 'getRenderDataVector'

    /home/d.vasilev/GVRFMerge/GearVRf-Tests/framework-tests/app/src/main/cpp/helpers.cpp: In function '_jlongArray* Java_org_gearvrf_tester_StateSortTests_getRenderDataVector(JNIEnv*, jclass)':
    /home/d.vasilev/GVRFMerge/GearVRf-Tests/framework-tests/app/src/main/cpp/helpers.cpp:7:78: error: 'class gvr::Renderer' has no member named 'getRenderDataVector'
       const std::vector<gvr::RenderData *> &renderDataVector = gvr::gRenderer->getRenderDataVector();

**Comment by liaxim** [comment]
I guess this test case could be considered obsolete. If we want to stress test something in 4.0 we probably need to devise different test.

**Comment by dnvasilev** [comment]
Removed tests. #201
